### ISSUE TITLE
Feature request : Add shortcut to reattach (undo)

### ISSUE THREAD

**Issue by fabien-michel** [Claymont/detach-tab#1]
Would be great to have a shortcut to undo detach and restore tab into previous window

**Comment by Claymont** [comment]
Thank you for the suggestion, and sorry for late reply.

Just uploaded a build here on GitHub with an added shortcut for reattaching tab, it reattaches to previous window and in its previous position.

I will do a couple of days of QA on it and then upload it to AMO.

**Comment by fabien-michel** [comment]
Good to know ! thanks you ! I can't try it for now as my Firefox won't let me install unsigned extensions.

**Comment by Claymont** [comment]
Updated version is now available on [AMO](https://addons.mozilla.org/en-US/firefox/addon/detach-tab/), as such I'm closing this.

Thanks again for the suggestion, and if you experience any bug please report it.

**Comment by JStyle21** [comment]
Hi
Sorry to bother you but is it possible to add the ability to control which window gets the reattached tab?
Sometimes one just needs to move tabs

**Comment by Claymont** [comment]
I would pretty much only consider adding a "move" feature if there are no other extension that can perform that function.

I'm a bit starved for time right now, please create a new issue with that feature request and I'll take a look at it later.
